
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION_BUILD = "true"

# Netlify Identity configuration
[identity]
  settings = true

# Git Gateway for Netlify CMS
[identity.git_gateway]
  enabled = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.netlify.com https://identity.netlify.com; frame-src 'self' https://identity.netlify.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for contact forms
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

# Admin redirect
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Old URL redirects (if needed)
[[redirects]]
  from = "/services"
  to = "/#services"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

# Form handling
[forms]
  settings = true

# Functions configuration
[functions]
  directory = "netlify/functions"

# Dev server configuration
[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
  framework = "#auto"

# Plugin configuration for optimization
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://your-domain.com"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing",
      "yandex"
    ]

# Environment variables (example)
# [context.production.environment]
#   VITE_SITE_URL = "https://your-domain.com"
#   VITE_PHONE_NUMBER = "+966501234567"

# Branch deploys
[context.branch-deploy]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"
