[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION_BUILD = "true"

# Netlify Identity settings
[identity]
  settings = true

# Enable new user registration
[identity.registration]
  enabled = true

# Git Gateway settings for CMS
[identity.git_gateway]
  enabled = true

# Identity settings for external providers
[identity.external]
  github = true
  google = true

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://identity-js.netlify.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.netlify.com https://identity.netlify.com https://*.netlify.com;"

# Cache optimization for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

# Admin panel redirect
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Forms handling
[forms]
  settings = true

# Functions configuration
[functions]
  directory = "netlify/functions"

# Development server
[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
